Upgrade actions/cache from v2 to v4.2.0 in nightly build workflow
skalenetwork/skale-manager pull request #1156
Opened 2024-12-16 18:21 UTC by yavrsky

* Updated `actions/cache` from `v2` to `v4.2.0` in multiple places

2024-12-16 19:08 UTC, DmytroNazarenko approved these changes, later dismissed

2024-12-19 15:51 UTC, DimaStebaev requested changes

2024-12-19 15:51 UTC, DimaStebaev commented on .github/workflows/nightly_build.yml
> +        cae: pip
Typo.

2024-12-20 14:49 UTC, DimaStebaev approved these changes

2024-12-26 15:49 UTC, DmytroNazarenko approved these changes

2024-12-26 15:53 UTC, merged