Enhancement/skale 2625 dkg refactoring
skalenetwork/skale-manager pull request #237
Opened 2020-05-27 07:17 UTC by DimaStebaev

Refactor DKG.
Remove assembly.
Use structures instead of bytes arrays.

2020-05-27 10:21 UTC, olehnikolaiev commented on contracts/SkaleDKG.sol
> +    struct VerificationVector {
this is not an array of Fp2 numbers, but an array of G2 points which of them is pair of Fp2 numbers

2020-05-27 10:23 UTC, olehnikolaiev commented on contracts/SkaleDKG.sol
> +        require(verificationVector.points.length >= 2, "2 points is needed for broadcast");
regarding to the previous comment this require should be changed - you obviously can send verification vector with length 1 (you should have `t` equal to 1 in this case)

2020-05-27 14:16 UTC, olehnikolaiev reviewed
lgtm

2020-05-27 14:16 UTC, olehnikolaiev commented on contracts/SkaleDKG.sol
> +        require(verificationVector.points.length % 2 == 0, "Verification vector contains odd number of points");
if you will change Verification Vector structure this require should be deleted

2020-05-28 14:10 UTC, olehnikolaiev submitted a review, later dismissed
good!

2020-06-03 09:57 UTC, payvint commented on contracts/Decryption.sol
> +        return bytes32(secretNumber) ^ key;
Wow

2020-06-05 11:13 UTC, payvint commented on contracts/MonitorsFunctionality.sol
> +        checkedNode.time = nodes.getNodeNextRewardDate(nodeIndex) - constantsHolder.deltaPeriod();
Maybe do a sub function by SafeMath?

2020-06-05 11:15 UTC, DimaStebaev commented on contracts/MonitorsFunctionality.sol
> +        checkedNode.time = nodes.getNodeNextRewardDate(nodeIndex) - constantsHolder.deltaPeriod();
I tried but there is no uint32 sub in SafeMath. Used assert instead.

2020-06-05 11:19 UTC, payvint commented on contracts/Nodes.sol
> +        bytes32[2] calldata publicKey,
Need to tell skale.py guys

2020-06-05 11:19 UTC, DimaStebaev commented on contracts/Nodes.sol
> +        bytes32[2] calldata publicKey,
I'll create an issue.

2020-06-05 12:08 UTC, payvint requested changes
Have some questions to the naming

2020-06-05 12:08 UTC, payvint commented on contracts/SkaleDKG.sol
> +    struct MultipliedShare {
Need to use G2Point instead of MultipliedShare and delete this structure

2020-06-05 12:08 UTC, payvint commented on contracts/SkaleDKG.sol
> +    struct Complex {
Also I think it would be better to rename it to Fp2 structure - as we use this structure as Fp2 point 
Overall Fp2 and complex numbers are not the same numbers

2020-06-05 12:08 UTC, payvint commented on contracts/SkaleDKG.sol
> +        KeyShare[] memory sc,
You could rename it too

2020-06-05 13:28 UTC, payvint approved these changes
Wow, nice updates!

2020-06-05 15:45 UTC, merged