Enhancement/skale 3070 hashing features
skalenetwork/skale-manager pull request #362
Opened 2020-08-21 14:46 UTC by payvint

SKALE-3070 Implemented Hashing features

2020-08-21 16:44 UTC, cstrangedk requested changes

2020-08-21 16:44 UTC, cstrangedk commented on contracts/KeyStorage.sol
> +    // Unused variable!!
Why not remove?

2020-08-21 16:44 UTC, cstrangedk commented on contracts/SkaleDKG.sol
> +        require(!dkgProcess[groupIndex].broadcasted[index], "This node is already broadcasted");
This node has...

2020-08-21 18:20 UTC, olehnikolaiev requested changes

2020-08-21 18:20 UTC, olehnikolaiev commented on contracts/KeyStorage.sol
> +    function _getData() private view returns (BroadcastedData memory) {
not needed

2020-08-24 09:39 UTC, payvint commented on contracts/KeyStorage.sol
> +    // Unused variable!!
We have already deployed contract to mainnet with this variable!

2020-08-24 09:39 UTC, payvint commented on contracts/SkaleDKG.sol
> +        require(!dkgProcess[groupIndex].broadcasted[index], "This node is already broadcasted");
Thanks:)

2020-08-24 09:40 UTC, payvint commented on contracts/KeyStorage.sol
> +    function _getData() private view returns (BroadcastedData memory) {
Yeah not needed but if we leave _data (contract deployed) we need to use this variable somewhere and I have created unused function

2020-08-24 10:17 UTC, cstrangedk approved these changes
lgtm

2020-08-24 12:02 UTC, merged