SKALE-3221 Remove requirement to be channel opened while deleting cha…
skalenetwork/skale-manager pull request #378
Opened 2020-09-08 17:46 UTC by yavrsky

…nnel

2020-09-09 11:26 UTC, kladkogex requested changes
Please add a unit test.

2020-10-05 07:30 UTC, DimaStebaev submitted a review, later dismissed

2020-10-06 10:20 UTC, DimaStebaev approved these changes

2020-10-06 10:24 UTC, payvint approved these changes
Nice!

2020-10-06 16:50 UTC, kladkogex approved these changes

2020-10-06 16:51 UTC, kladkogex commented
Travis build is failing

2020-10-07 01:42 UTC, merged