SKALE-3508 Fix range check for signature
skalenetwork/skale-manager pull request #456
Opened 2020-12-20 22:55 UTC by yavrsky

2020-12-21 09:25 UTC, DimaStebaev commented
Why not add this check to `skaleVerifier.verify` function? It's external and may be called outside with wrong arguments.

2020-12-21 10:04 UTC, DimaStebaev requested changes
1. add coordinates check to `skaleVerifier.verify` function
2. process a case when a > 0 and b == 0 correctly

2020-12-21 18:37 UTC, payvint approved these changes, later dismissed
Nice!

2020-12-23 11:27 UTC, DimaStebaev approved these changes

2020-12-23 11:28 UTC, payvint approved these changes

2020-12-23 11:29 UTC, merged