Add schain to address map
skalenetwork/skale-manager pull request #835
Opened 2022-06-11 10:04 UTC by payvint

2022-06-17 15:20 UTC, DimaStebaev requested changes

2022-06-17 15:20 UTC, DimaStebaev commented on contracts/SchainsInternal.sol
> +    function _addAddressToSchain(bytes32 schainHash, address nodeAddress) internal virtual returns (bool) {
What about adding of `schainExists` modifier?

2022-06-17 15:20 UTC, DimaStebaev commented on contracts/SchainsInternal.sol
> +    function _removeAddressFromSchain(bytes32 schainHash, address nodeAddress) internal virtual returns (bool) {
What about adding of `schainExists` modifier?

2022-06-17 15:20 UTC, DimaStebaev commented on contracts/test/SchainsInternalMock.sol
> +    function _addAddressToSchain(bytes32, address) internal override returns (bool) {
Must be `pure`

2022-06-17 15:20 UTC, DimaStebaev commented on contracts/test/SchainsInternalMock.sol
> +    function _removeAddressFromSchain(bytes32, address) internal override returns (bool) {
Must be `pure`.

2022-06-17 15:20 UTC, DimaStebaev commented on dictionaries/names.txt
> +yavorsky
What was changed?

2022-06-17 15:20 UTC, DimaStebaev commented on slither.config.json
> +    "detectors_to_exclude": "similar-names,reentrancy-events,solc-version,assembly,timestamp,calls-loop,reentrancy-no-eth,public-mappings-nested,incorrect-equality,dead-code",
I'm not sure to that ignoring `dead-code` is a good idea.

2022-06-17 15:20 UTC, DimaStebaev commented on contracts/SchainsInternal.sol
> +    mapping (bytes32 => EnumerableSetUpgradeable.AddressSet) private _nodeAddressInSchain;
This mapping requires initialization during an upgrade.

2022-06-24 09:12 UTC, DimaStebaev reviewed
Looks norm.

2022-06-24 09:37 UTC, DimaStebaev approved these changes

2022-06-24 11:03 UTC, yavrsky approved these changes

2022-06-24 11:08 UTC, kladkogex approved these changes

2022-06-24 11:14 UTC, gannakulikova approved these changes

2022-06-24 11:14 UTC, PolinaKiporenko approved these changes

2022-06-24 11:15 UTC, merged